name: SSH Deploy to Ubuntu VPS

on: 
 push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{secrets.CONTABO_SSH_01232023_1}}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: "crudphpjquery.alenev.name"
          REMOTE_USER: "admin"
          SOURCE: ""
          TARGET: "/home/admin/web/crudphpjquery.alenev.name/public_html"
          EXCLUDE: "/.git/, /.github/, config.php, telenorma.sql"